// Decompiled with JetBrains decompiler
// Type: BlueStacks.Common.DataManagerCodes
// Assembly: HD-Common, Version=4.250.0.1070, Culture=neutral, PublicKeyToken=null
// MVID: 7033AB66-5028-4A08-B35C-D9B2B424A68A
// Assembly location: C:\Program Files\BlueStacks\HD-Common.dll

namespace BlueStacks.Common
{
  public enum DataManagerCodes
  {
    USER_CANCELLED_ON_RESTORE_WARNING = -20, // 0xFFFFFFEC
    BACKUP_VERSION_GREATER_THAN_CURRENT_BUILD_VERSION = -19, // 0xFFFFFFED
    BACKUP_FROM_KK_BUILD = -18, // 0xFFFFFFEE
    EXCEPTION_IN_RESTORE = -17, // 0xFFFFFFEF
    EXIT_AS_USERINFO_FILE_MISSING_IN_BACKUP = -16, // 0xFFFFFFF0
    ERROR_IN_CHANGING_CONFIGURATION_FILES = -15, // 0xFFFFFFF1
    BACKUP_INFO_FILE_NOT_EXIST = -14, // 0xFFFFFFF2
    ERROR_IN_MOVING_EXISTING_DATA_TO_TEMP = -13, // 0xFFFFFFF3
    USER_CANCELLED_DUE_TO_CFG_FILE = -12, // 0xFFFFFFF4
    EXIT_AS_BACKUP_VERSION_IS_HIGHER_THAN_CURRENT = -11, // 0xFFFFFFF5
    INSUFFICIENT_DISK_SPACE = -10, // 0xFFFFFFF6
    INVALID_OEM = -9, // 0xFFFFFFF7
    WRONG_PATH_CHOSEN = -8, // 0xFFFFFFF8
    EXCEPTION_IN_BACKUP = -7, // 0xFFFFFFF9
    ERROR_IN_CREATING_USERINFO_FILE_WHILE_BACKUP = -6, // 0xFFFFFFFA
    ERROR_IN_CREATING_BACKUP_INVALID_PATH_SELECTED = -5, // 0xFFFFFFFB
    BACKUP_CANCELLED_DURING_PROCESS = -4, // 0xFFFFFFFC
    NO_PATH_CHOSEN = -3, // 0xFFFFFFFD
    CANCEL = -2, // 0xFFFFFFFE
    DEFAULT = -1, // 0xFFFFFFFF
    SUCCESS = 0,
  }
}
