// Decompiled with JetBrains decompiler
// Type: BlueStacks.Common.GuestApkInstallFailCodes
// Assembly: HD-Common, Version=4.250.0.1070, Culture=neutral, PublicKeyToken=null
// MVID: 7033AB66-5028-4A08-B35C-D9B2B424A68A
// Assembly location: C:\Program Files\BlueStacks\HD-Common.dll

namespace BlueStacks.Common
{
  public enum GuestApkInstallFailCodes
  {
    INSTALL_FAILED_INVALID_XAPK_VERSION = -204, // 0xFFFFFF34
    INSTALL_FAILED_APK_EXTRACTION_FAILED = -203, // 0xFFFFFF35
    INSTALL_FAILED_EXPANSION_FILE_FAILED = -202, // 0xFFFFFF36
    INSTALL_FAILED_EXPANSION_FILE_INVALID = -201, // 0xFFFFFF37
    INSTALL_FAILED_INVALID_XAPK = -200, // 0xFFFFFF38
    INSTALL_FAILED_EPHEMERAL_INVALID = -116, // 0xFFFFFF8C
    INSTALL_FAILED_ABORTED = -115, // 0xFFFFFF8D
    INSTALL_FAILED_NO_MATCHING_ABIS = -113, // 0xFFFFFF8F
    INSTALL_FAILED_DUPLICATE_PERMISSION = -112, // 0xFFFFFF90
    INSTALL_FAILED_USER_RESTRICTED = -111, // 0xFFFFFF91
    INSTALL_FAILED_INTERNAL_ERROR = -110, // 0xFFFFFF92
    INSTALL_PARSE_FAILED_MANIFEST_EMPTY = -109, // 0xFFFFFF93
    INSTALL_PARSE_FAILED_MANIFEST_MALFORMED = -108, // 0xFFFFFF94
    INSTALL_PARSE_FAILED_BAD_SHARED_USER_ID = -107, // 0xFFFFFF95
    INSTALL_PARSE_FAILED_BAD_PACKAGE_NAME = -106, // 0xFFFFFF96
    INSTALL_PARSE_FAILED_CERTIFICATE_ENCODING = -105, // 0xFFFFFF97
    INSTALL_PARSE_FAILED_INCONSISTENT_CERTIFICATES = -104, // 0xFFFFFF98
    INSTALL_PARSE_FAILED_NO_CERTIFICATES = -103, // 0xFFFFFF99
    INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION = -102, // 0xFFFFFF9A
    INSTALL_PARSE_FAILED_BAD_MANIFEST = -101, // 0xFFFFFF9B
    INSTALL_PARSE_FAILED_NOT_APK = -100, // 0xFFFFFF9C
    INSTALL_FAILED_PERMISSION_MODEL_DOWNGRADE = -26, // 0xFFFFFFE6
    INSTALL_FAILED_VERSION_DOWNGRADE = -25, // 0xFFFFFFE7
    INSTALL_FAILED_UID_CHANGED = -24, // 0xFFFFFFE8
    INSTALL_FAILED_PACKAGE_CHANGED = -23, // 0xFFFFFFE9
    INSTALL_FAILED_VERIFICATION_FAILURE = -22, // 0xFFFFFFEA
    INSTALL_FAILED_VERIFICATION_TIMEOUT = -21, // 0xFFFFFFEB
    INSTALL_FAILED_MEDIA_UNAVAILABLE = -20, // 0xFFFFFFEC
    INSTALL_FAILED_INVALID_INSTALL_LOCATION = -19, // 0xFFFFFFED
    INSTALL_FAILED_CONTAINER_ERROR = -18, // 0xFFFFFFEE
    INSTALL_FAILED_MISSING_FEATURE = -17, // 0xFFFFFFEF
    INSTALL_FAILED_CPU_ABI_INCOMPATIBLE = -16, // 0xFFFFFFF0
    INSTALL_FAILED_TEST_ONLY = -15, // 0xFFFFFFF1
    INSTALL_FAILED_NEWER_SDK = -14, // 0xFFFFFFF2
    INSTALL_FAILED_CONFLICTING_PROVIDER = -13, // 0xFFFFFFF3
    INSTALL_FAILED_OLDER_SDK = -12, // 0xFFFFFFF4
    INSTALL_FAILED_DEXOPT = -11, // 0xFFFFFFF5
    INSTALL_FAILED_REPLACE_COULDNT_DELETE = -10, // 0xFFFFFFF6
    INSTALL_FAILED_MISSING_SHARED_LIBRARY = -9, // 0xFFFFFFF7
    INSTALL_FAILED_SHARED_USER_INCOMPATIBLE = -8, // 0xFFFFFFF8
    INSTALL_FAILED_UPDATE_INCOMPATIBLE = -7, // 0xFFFFFFF9
    INSTALL_FAILED_NO_SHARED_USER = -6, // 0xFFFFFFFA
    INSTALL_FAILED_DUPLICATE_PACKAGE = -5, // 0xFFFFFFFB
    INSTALL_FAILED_INSUFFICIENT_STORAGE = -4, // 0xFFFFFFFC
    INSTALL_FAILED_INVALID_URI = -3, // 0xFFFFFFFD
    INSTALL_FAILED_INVALID_APK = -2, // 0xFFFFFFFE
    INSTALL_FAILED_ALREADY_EXISTS = -1, // 0xFFFFFFFF
  }
}
