// Decompiled with JetBrains decompiler
// Type: BlueStacks.Common.ClientHotKeys
// Assembly: HD-ServiceInstaller, Version=4.250.0.1070, Culture=neutral, PublicKeyToken=null
// MVID: 15F93427-26B3-4C7E-BAB1-0A00688BC4D4
// Assembly location: C:\Program Files\BlueStacks\HD-ServiceInstaller.exe

namespace BlueStacks.Common
{
  public enum ClientHotKeys
  {
    STRING_TOGGLE_KEYMAP_WINDOW,
    STRING_TOGGLE_FARM_MODE,
    AddWebTab,
    STRING_TOGGLE_OVERLAY,
    STRING_UPDATED_FULLSCREEN_BUTTON_TOOLTIP,
    STRING_TOGGLE_LOCK_CURSOR,
    RestoreWindow,
    STRING_TOGGLE_KEYMAPPING_STATE,
    STRING_TRANSLATOR_TOOL,
    STRING_ALWAYS_ON_TOP,
    STRING_INCREASE_VOLUME,
    STRING_DECREASE_VOLUME,
    STRING_TOGGLE_MUTE_STATE,
    STRING_TOOLBAR_CAMERA,
    STRING_MACRO_RECORDER,
    STRING_SYNCHRONISER,
    STRING_TOGGLE_VIDEO_RECORDER,
    STRING_RECORD_SCREEN,
    STRING_HOME,
    STRING_BACK,
    STRING_SHAKE,
    STRING_ROTATE,
    STRING_OPEN_MEDIA_FOLDER,
    STRING_TOGGLE_MULTIINSTANCE_WINDOW,
    STRING_BOSSKEY_SETTING,
    STRING_SET_LOCATION,
    STRING_GAMEPAD_CONTROLS,
    STRING_MINIMIZE_TOOLTIP,
    STRING_AUTOMATIC_SORTING,
    STRING_START_STREAMING,
    STRING_SETTINGS,
    STRING_CONTROLS_EDITOR,
    STRING_IMAGE_PICKER,
    STRING_UNLOCK_MOUSE,
    STRING_UTC_CONVERTER,
    STRING_INSTALL_APK,
    STRING_SWITCH_OVERLAY_CONTROLS,
    STRING_TOGGLE_MICROPHONE_MUTE_STATE,
  }
}
