// Decompiled with JetBrains decompiler
// Type: BlueStacks.Common.InstallerCodes
// Assembly: HD-ServiceInstaller, Version=4.250.0.1070, Culture=neutral, PublicKeyToken=null
// MVID: 15F93427-26B3-4C7E-BAB1-0A00688BC4D4
// Assembly location: C:\Program Files\BlueStacks\HD-ServiceInstaller.exe

namespace BlueStacks.Common
{
  public enum InstallerCodes
  {
    TEST_ROLLBACK_FAIL = -256, // 0xFFFFFF00
    TEST_ROLLBACK = -255, // 0xFFFFFF01
    FAILED_TO_BUILD_HYPERV_CONFIGS = -60, // 0xFFFFFFC4
    UNABLE_TO_STOP_SERVICE_BEFORE_UNINSTALLING = -59, // 0xFFFFFFC5
    ERROR_WHILE_UNINSTALLING_SERVICE = -58, // 0xFFFFFFC6
    GAMEDATA_DEPLOY_FAILED = -57, // 0xFFFFFFC7
    UNHANDLED_EXCEPTION = -56, // 0xFFFFFFC8
    ROLLBACK_PROGRAMDATA_FAILED = -55, // 0xFFFFFFC9
    ROLLBACK_PROGRAMFILES_FAILED = -54, // 0xFFFFFFCA
    ROLLBACK_REGISTRY_FAILED = -53, // 0xFFFFFFCB
    ROLLBACK_FRESH_FAILED = -52, // 0xFFFFFFCC
    FAILED_TO_RENAME_NEW_ITEMS = -51, // 0xFFFFFFCD
    FAILED_TO_MOVE_OLD_ITEMS = -49, // 0xFFFFFFCF
    FAILED_TO_RESTORE_ANDROID_DATA = -46, // 0xFFFFFFD2
    FAILED_TO_RESTORE_CLIENT_DATA = -45, // 0xFFFFFFD3
    OLD_DATA_DIR_DOESNT_EXIST = -44, // 0xFFFFFFD4
    FAILED_TO_RESERVE_HTTP_PORTS = -43, // 0xFFFFFFD5
    FAILED_TO_CREATE_VMCONFIG = -42, // 0xFFFFFFD6
    FAILED_TO_CREATE_BSTKGLOBAL = -41, // 0xFFFFFFD7
    FAILED_TO_INSTALL_DRIVER = -40, // 0xFFFFFFD8
    ENGINE_FILES_DEPLOY_FAILED = -39, // 0xFFFFFFD9
    LOCALE_FILES_DEPLOY_FAILED = -38, // 0xFFFFFFDA
    CEF_DATA_DEPLOY_FAILED = -37, // 0xFFFFFFDB
    CLIENT_FILES_DEPLOY_FAILED = -36, // 0xFFFFFFDC
    PROGRAM_DATA_ZIP_EXTRACT_FAILED = -35, // 0xFFFFFFDD
    PROGRAM_FILES_ZIP_EXTRACT_FAILED = -33, // 0xFFFFFFDF
    FAILED_TO_RESTORE_REGISTRY_DATA = -32, // 0xFFFFFFE0
    FAILED_CREATING_REGISTRY = -31, // 0xFFFFFFE1
    SERVICE_MARKED_FOR_DELETION = -30, // 0xFFFFFFE2
    HYPER_V_COMPUTE_PLATFORM_NOTAVAIL = -20, // 0xFFFFFFEC
    HYPER_V_DISABLED = -19, // 0xFFFFFFED
    HYPER_V_ENABLED = -18, // 0xFFFFFFEE
    VTX_DISABLED = -17, // 0xFFFFFFEF
    SERVICE_RUNNING_EXIT = -16, // 0xFFFFFFF0
    BLUESTACKS_POSSIBLY_CORRUPT = -15, // 0xFFFFFFF1
    INSUFFICIENT_DISKSPACE = -14, // 0xFFFFFFF2
    REGISTRY_EDITING_DISABLED = -13, // 0xFFFFFFF3
    GL_UNSUPPORTED = -12, // 0xFFFFFFF4
    INSUFFICIENT_PHYSICALMEMORY = -11, // 0xFFFFFFF5
    OS_VERSION_NOT_SUPPORTED = -10, // 0xFFFFFFF6
    CANCELLED_WHILE_INSUFFICIENT_STORAGE = -9, // 0xFFFFFFF7
    DISALLOWED_CHARS_IN_DIR = -8, // 0xFFFFFFF8
    CANCELLED_PRESERVE_KEYMAPPINGS = -7, // 0xFFFFFFF9
    CANCELLED_WHILE_UPGRADE = -6, // 0xFFFFFFFA
    COMMON_UTILS_EXTRACT_FAILED = -5, // 0xFFFFFFFB
    UPGRADE_NOT_SUPPORTED = -4, // 0xFFFFFFFC
    VERSION_DOWNGRADE = -3, // 0xFFFFFFFD
    INSTALLERPROPERTIES_INIT_FAILED = -2, // 0xFFFFFFFE
    INSTALLER_ALREADY_RUNNING = -1, // 0xFFFFFFFF
    INCOMPATIBLE_ARCHITECTURE_INSTALLER_STARTED = 0,
    SUCCESS = 0,
    LAUNCH_BLUESTACKS_ON_SUCCESSFUL_INSTALLATION = 2,
    EXITING_WITHOUT_ADDING_USER_TO_HYPERV_ADMIN_GROUP = 3,
    EXITING_AFTER_ADDING_USER_TO_HYPERV_ADMIN_GROUP = 4,
  }
}
